apiVersion: v1
kind: Secret
metadata:
  name: custom-enduro-secret
type: Opaque
stringData:
  custom-enduro-worker.toml: |
    debug = true
    verbosity = 2

    [temporal]
    address = "temporal-frontend.enduro-sdps:7233"
    namespace = "default"

    [worker]
    taskQueue = "custom-enduro"
    maxConcurrentSessions = 1

    [preprocessing]
    workflowName = "preprocessing"
    sharedPath = "/home/enduro/shared"

    [preprocessing.bagCreate]
    checksumAlgorithm = "sha512"
