apiVersion: v1
kind: Secret
metadata:
  name: custom-enduro-secret
type: Opaque
stringData:
  custom-enduro-worker.toml: |
    debug = true
    verbosity = 2

    sharedPath = "/home/enduro/shared"

    [temporal]
    address = "temporal-frontend.enduro-sdps:7233"
    namespace = "default"
    taskQueue = "preprocessing"
    workflowName = "preprocessing"

    [worker]
    maxConcurrentSessions = 1

    [bagit]
    checksumAlgorithm = "sha512"
