name: Gosec
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "45 11 * * 0"
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
        cache: true
    - name: Run Gosec Security Scanner
      run: make gosec
