name: Nightly

on:
  workflow_dispatch: {}
  schedule:
    # Daily, at 1pm UTC / 6am PST.
    - cron: "0 13 * * *"

jobs:
  govulncheck:
    name: Go vulnerability check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest
      - name: Execute govulncheck
        run: govulncheck ./...
